### ISSUE TITLE
Quizzes

### ISSUE THREAD

**Issue by AnomalyJx** [SpiritXmas/Uplearn-XP-Farm#1]
I don't know if you are intending on coding the program to auto spoof quizzes too, but that would be a great addition to the uplearn cheat. Other than that, it works perfectly for the videos.

**Comment by SpiritXmas** [comment]
Unfortunately with quizzes, the responses aren't stored on the client so there's no way of grabbing them. No plans at the moment to do anything with quizzes, although if I revisit this project in the future implementing some automatic quiz solver with AI would be viable.
